
configuration: Debug
image: Visual Studio 2017

before_build:
  - nuget restore
  
build:
  project: EasyMotion.sln
  verbosity: minimal

artifacts:
  - path: Src\EasyMotion\bin\Debug\EasyMotion.vsix

